### PR TITLE
Added TypeScript type definitions

### PR DESCRIPTION
**Pull request by VitorLuizC**
I've added TypeScript type definitions file and it's entry on `package.json`. I've also ran `yarn lint` and fixed flow types because they are throwing errors on `yarn flow` command.

> There are no issues related or some screenshot/GIF appropriate to this.

- [x] I ran `yarn lint` and `yarn flow`

### CODE REVIEW

**Comment by VitorLuizC** [comment]
I'm closing this to add this type definitons on [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped) instead.

**Comment by smkhalsa** [comment]
@VitorLuizC I wasn't able to find the types on DefinitelyTyped. Did you publish them?

**Comment by VitorLuizC** [comment]
No, I declared it locally...

You can add it to your project typings, btw.

```ts
declare module 'react-native-sideswipe' {
  import { Component, ReactNode } from 'react';
  import { StyleProp, ViewStyle, Animated } from 'react-native';

  type SideSwipeGestureState = {
    stateID: number;
    moveX: number;
    moveY: number;
    x0: number;
    y0: number;
    dx: number;
    dy: number;
    vx: number;
    vy: number;
    numberActiveTouches: number;
  };

  type SideSwipeRenderProps<T> = {
    /**
     * index of item in data collection.
     */
    itemIndex: number;

    /**
     * active index of the carousel.
     */
    currentIndex: number;

    /**
     * total count of items in data collection.
     */
    itemCount: number;

    /**
     * item passed from FlatList.
     */
    item: T;

    // animated value tracking current index.
    animatedValue: Animated.Value;
  };

  type SideSwipeProps<T> = {
    /**
     * applied to the content container within FlatList.
     * ```
     * |------------ [ style ]--------------------------|
     * | |---------- [ flatListStyle ] ---------------| |
     * | | |-------- [ contentContainerStyle ] -----| | |
     * ```
     */
    contentContainerStyle?: StyleProp<ViewStyle>;

    /**
     * This will equal the padding added to both left and right of itemWidth.
     * ```js
     * const contentOffset = (viewport.width - itemWidth) / 2
     * ```
     */
    contentOffset?: number;

    /**
     * data for FlatList
     */
    data: Array<T>;

    /**
     * used to set the unique key of each item in the carousel.
     */
    extractKey?: (item: T, index: number) => string;

    /**
     * applied to the content container within the content container.
     * ```
     * |------------ [ style ]--------------------------|
     * | |---------- [ flatListStyle ] ---------------| |
     * | | |-------- [ contentContainerStyle ] -----| | |
     * ```
     */
    flatListStyle?: StyleProp<ViewStyle>;

    /**
     * active index of the carousel.
     */
    index?: number;

    /**
     * This is the total width of everything that should be centered when in view.
     * tip: be sure to include any margin added to the left and right of the item.
     */
    itemWidth?: number;

    /**
     * function called when the end of the carousel is reached.
     */
    onEndReached?: () => void;

    /**
     * number between 0 - 1 used to determine when to call onEndReached.
     */
    onEndReachedThreshold?: number;

    /**
     * fired when the active index for the carousel changes.
     */
    onIndexChange?: (index: number) => void;

    /**
     * offset from center of carousel item used for determining index.
     * drag distance examples with different thresholds
     * ```
     * with item width of 200 and no threshold
     * ---------------> <-----------------
     * 0 ------- -index/+index ------- 200
     *
     * with item width of 200 and 50 threshold
     * ---------->           <------------
     * 0 -- -index -- 100 -- +index -- 200
     *
     * with item width of 200 and 75 threshold
     * -------->               <----------
     * 0 - -index --- 100 --- +index - 200
     *
     * with item width of 200 and 90 threshold
     * ----->                      <------
     * 0 -index ----- 100 ----- +index 200
     * ```
     */
    threshold?: number;

    /**
     * to determine the index use the velocity of the gesture.
     */
    useVelocityForIndex?: boolean;

    /**
     * render item method, similar to FlatList with some enhancements.
     */
    renderItem: (props: SideSwipeRenderProps<T>) => ReactNode;

    /**
     * should we capture touch event.
     */
    shouldCapture?: (state: SideSwipeGestureState) => boolean;

    /**
     * should we release touch event to another view.
     */
    shouldRelease?: (state: SideSwipeGestureState) => boolean;

    /**
     * style for the FlatList wrapper View
     * ```
     * |------------ [ style ]--------------------------|
     * | |---------- [ flatListStyle ] ---------------| |
     * | | |-------- [ contentContainerStyle ] -----| | |
     * ```
     */
    style?: StyleProp<ViewStyle>;

    /**
     * should we use native driver for animation.
     */
    useNativeDriver?: boolean;
  };

  class SideSwipe<T> extends Component<SideSwipeProps<T>> {}

  export { SideSwipeGestureState, SideSwipeRenderProps, SideSwipeProps };

  export default SideSwipe;
}
```

**Comment by smkhalsa** [comment]
Thanks @VitorLuizC. Yea, I already added the typings from your PR to my project manually. For the benefit of the community, can we go ahead and make a PR for these into DefinitelyTyped?

**Comment by VitorLuizC** [comment]
Would be nice to have types here, but the maintainer is very absent...

**Comment by iagobelo** [comment]
Please merge it!

**Comment by LoicMahieu** [comment]
Thanks @VitorLuizC 
Works very well!

@kkemple Is there any change to merge this PR ?

**Comment by kkemple** [comment]
I've been looking for maintainers and no one wants to take it on. happy to add someone as a maintainer so im not a blocker as I rarely work in RN these days.

**Pull request merged**
