### PR TITLE
added scroll begin and end event handlers as props

### PR DESCRIPTION
**Pull request by austenLacy**
### What did you do:

Added `onScrollBeginDrag` and `onScrollEndDrag` from `ScrollView` prop as carousel props .

### Does this relate to an open issue? If so which one?

No

### Screenshots:

None

### Checklist:

- [x] I added link to related issue if there is one
- [x] I added a screenshot/gif (if appropriate)
- [x] I ran `yarn lint` and `yarn flow`

### CODE REVIEW

**Comment by austenLacy** [comment]
UPDATE: I'm testing this now in a project and the `onScrollBeginDrag` and `onScrollEndDrag` handlers don't seem to be called. My use case is a side swipe list nested inside of a ScrollView which might be causing issues as RN has had problems with that in the past. Ultimately my goal is disable the parent ScrollView when swiping right/left.

**Comment by austenLacy** [comment]
I think I'm going to close this for now because I can't seem to get it to trigger the drag handlers

**Comment by kkemple** [comment]
ah, because scrolling is disabled! it's powered by panresponder so instead we expose`onPanResponderGrant` and `onPanResponderRelease` into userland, then you could disable/enable scrollview from there.

are you currently having issues using this in a scrollview?

**Comment by austenLacy** [comment]
That makes a lot more sense now. I haven't had any other issues with using it in a ScrollView. Thanks for the quick reply!

**Pull request closed without merging**
